stages:
  - prepare
  - build
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# ================= PREPARE =================
prepare:
  stage: prepare
  image: maven:3.9-eclipse-temurin-17

  script:
    - apt-get update && apt-get install -y git
    - mkdir -p .m2/repository

    # ✅ Clone depuis GitHub (public)
    - git clone https://github.com/mbayangdrame/product-core.git

    # Installer product-core
    - cd product-core
    - mvn clean install -DskipTests
    - cd ..

  artifacts:
    paths:
      - .m2/repository

# ================= BUILD =================
build:
  stage: build
  image: maven:3.9-eclipse-temurin-17

  dependencies:
    - prepare

  script:
    - mvn clean package -DskipTests

  artifacts:
    paths:
      - target/*.jar

# ================= DOCKER =================
docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind

  dependencies:
    - build

  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest