stages:
  - test
  - build
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - mkdir -p ~/.m2
    - |
      cat > ~/.m2/settings.xml << EOF
      <settings>
        <servers>
          <server>
            <id>github</id>
            <username>mbayangdrame</username>
            <password>${GITHUB_TOKEN}</password>
          </server>
        </servers>
      </settings>
      EOF
    - mvn test -DskipTests
  cache:
    paths:
      - .m2/repository

build:
  stage: build
  image: maven:3.9-eclipse-temurin-17

  script:
    - apt-get update && apt-get install -y git

    # 🔥 Cloner product-core
    - git clone https://gitlab.com/mbayangdrame/product-core.git

    # 🔥 Vérifier contenu
    - ls product-core

    # 🔥 Installer product-core dans .m2
    - cd product-core
    - mvn clean install -DskipTests

    # 🔥 Vérification installation réelle
    - ls ~/.m2/repository/sn/isi/l3gl/core/product-core/0.3.0 || echo "❌ NOT INSTALLED"

    - cd ..

    # 🔥 Build product-api
    - mvn clean package -DskipTests

docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  dependencies:
    - build